2022_07/leetcode/2022_07_14_leetcode_332_yoon.py
패배했다 dfs어렵네... 아이디어? 푸는 방식 떠올리는게 빡시다
=> leetcode 332

2022_07/leetcode/2022_07_18_leetcode 5_hyeong_(S10) 슬라이딩 윈도우.py, 2022_07/leetcode/2022_07_24_leetcode200_hyeong_(S30).py
=> 2022_07_18_leetcode Longest Palindromic Substring_Medium_hyeong_(S10)

2022_07/leetcode/2022_07_24_leetcode200_hyeong_(S30).py
[:)](https://leetcode.com/problems/number-of-islands/)
=> 2022_07_24_leetcode200_hyeong_(S30).py

2022_07/programmers/2022_07_24_programmers_추석 트래픽_hyeong(S50).py
=> 2022_07_24_programmers_추석 트래픽_hyeong(S50)

2022_07/programmers/2022_07_30_programmers_멀리뛰기_hyeong(S0).py
=> 2022_07/programmers/2022_07_30_programmers_hyeong(S0)

2022_08/programmers/2022_08_07_programmers_파일명정렬_hyeong(S80).py
=> 2022_08_07_programmers_파일명정렬_hyeong(S80)

2022_07/leetcode/2022_07_24_leetcode200_hyeong_(S30).py, 2022_07/programmers/2022_07_24_programmers_추석 트래픽_hyeong(50).py, 2022_07/programmers/2022_07_30_programmers_멀리뛰기_hyeong(S0).py, 2022_08/programmers/2022_09_02_programmers_구명보트_hyeong(S70).py
아 ; 실수로 merge 안하고 해버렸네 ;
맨 밑에 구명보트만 봐주세요...
cli로만 해보려다가 요래 돼 버렸음
=> 2022_08/programmers/2022_09_02_programmers_구명보트_hyeong(S70)

2022_08/programmers/2022_08_28_programmers_등산코스 정하기(hyeong).py
2022_08_28_programmers_등산코스 정하기(hyeong)
=> 2022_08_28_programmers_등산코스 정하기(hyeong)

2022_09/programmers/2022_09_05_programmers_배달_hyeong.py
=> 2022_09_05_programmers_배달_hyeong

2022_07/leetcode/2022_07_18_leetcode 5_hyeong_(S10) 슬라이딩 윈도우.py, 2022_09/leetcode/2022_09_04_leetcode_787_hyeong.py
=> 2022_09_04_leetcode_787_Cheapest Flights Within K Stops

2022_09/leetcode/2022_09_05_leetcode_743_yoon.py, 2022_09/programmers/2022_09_05_programmers_배달_yoon.py
=> 2022/09 2주차 issue풀이- leetcode 743, programmers 배달

2022_09/leetcode/2022_09_05_leetcode_743_hyeong.py
=> 2022_09_05_leetcode_743_hyeong

2022_09/leetcode/2022_09_06_백준_KCM Travel_hyeong.py
2022_09_06_백준_KCM Travel_hyeong
어려웡 ㅠ
=> 2022_09_06_백준_KCM Travel_hyeong

2022_07/leetcode/2022_07_25_leetcode_46_yoon.py, 2022_07/leetcode/2022_07_25_leetcode_77_yoon.py
=> leetcode 46 & 77 풀이

2022_09/programmers/2022_09_17_proogrammers_N으로표현_flashdragon.cpp, 2022_09/programmers/2022_09_17_proogrammers_사칙연산_flashdragon.cpp
=> 프로그래머스문제들추가

2022_10/programmers/2022_10_07_programmers_입국심사_hyeong.py, 2022_10/programmers/2022_10_07_programmers_징검다리건너기_hyeong.py
2022_10_07_programmers_입국심사_hyeong, 2022_10_07_programmers_징검다리건너기_hyeong
=> 2022_10_07_programmers_입국심사_hyeong, 2022_10_07_programmers_징검다리건너기_hyeong

2022_11/programmers/2022_11_16_programmers_가장 먼 노드_hyeong.py
2022_11_16_programmers_가장 먼 노드_hyeong
=> 2022_11_16_programmers_가장 먼 노드_hyeong

2022_11/programmers/2022_11_08_programmers_가장먼노드_yoon.py
=> 11월 2주차 이슈 풀이:  가장먼노드

2022_11/programmers/2022_11_18_programmers_부대복귀_hyeong.py
2022_11_18_programmers_부대복귀_hyeong
=> 2022_11_18_programmers_부대복귀_hyeong

2022_12/programmers/2022_12_31_programmers_기지국설치_yoon.py, 2022_12/programmers/2022_12_31_programmers_유사칸토어_yoon.py
기지국 설치: https://school.programmers.co.kr/learn/courses/30/lessons/12979
유사 칸토어 비트열: https://school.programmers.co.kr/learn/courses/30/lessons/148652
=> 2022년 마지막 알고리즘 문제: 기지국 설치 & 유사 칸토어 비트열

2023_01/progammers/2023_01_02_programmers_카운트다운_yoon.py, 2023_01/progammers/2023_01_08_programmers_미로탈출명령어_yoon.py, 2023_01/progammers/2023_01_15_programmers_택배배달과수거하기_yoon.py, 2023_01/progammers/2023_01_15_programmers_표현가능한이진트리_yoon.py
python, javascript풀이
링크: https://school.programmers.co.kr/learn/courses/30/lessons/131129?language=python3
=> 1월 1주차 문제: 카운트다ì운(Dynamic programming문제)

2023_01/progammers/2023_01_28_programmers_뒤에있는큰 수 찾기_level2_hyeong.py
2023_01_28_programmers_뒤에있는큰 수 찾기_level2_hyeong
=> 2023_01_28_programmers_뒤에있는큰 수 찾기_level2_hyeong

2023_01/progammers/2023_01_28_programmers_인사고과_level3_hyeong.py
2023_01_28_programmers_인사고과_level3_hyeong
=> 2023_01_28_programmers_인사고과_level3_hyeong

2023_01/progammers/2023_01_28_programmers_뒤에있는큰 수 찾기_level2_hyeong.py, 2023_02/programmers/2023_02_09_programmers_가장긴펠린드롬_hyeong.py
2023_02_09_programmers_가장긴펠린드롬_hyeong
=> Carrot_2023_02_09_programmers_가장긴펠린드롬_hyeong
